# Generated by Django 2.1.5 on 2019-04-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('hit_points', models.CharField(blank=True, default='', max_length=5)),
                ('armor', models.CharField(blank=True, default='', max_length=5)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('damage', models.CharField(blank=True, default='', max_length=4)),
                ('aoe_distance', models.CharField(blank=True, default='', max_length=4)),
                ('charges', models.CharField(blank=True, default='', max_length=4)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('range', models.CharField(choices=[('short', 'Short'), ('short-medium', 'Short to Medium'), ('medium', 'Medium'), ('medium-long', 'Medium to Long'), ('long', 'Long'), ('unknown', 'Unknown')], max_length=32)),
                ('damage', models.CharField(blank=True, default='', max_length=4)),
                ('ammo', models.CharField(blank=True, default='', help_text="Put 'melee' if melee weapon.", max_length=5)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='aoe_distance',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='ability',
            name='charges',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='ability',
            name='damage',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='ability',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ability',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ability',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='target',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('target', 'Target')], max_length=32),
        ),
        migrations.AddField(
            model_name='ability',
            name='turns',
            field=models.CharField(blank=True, default='', help_text='Number of turns the ability lasts.', max_length=4),
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='character',
            name='hit_points',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='character',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='weapon',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character'),
        ),
        migrations.AddField(
            model_name='item',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character'),
        ),
        migrations.AddField(
            model_name='gear',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character'),
        ),
    ]
