# Generated by Django 2.1.5 on 2019-04-08 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EtherSplitApp', '0002_auto_20190408_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name_plural': 'Gear'},
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
