# Generated by Django 2.1.5 on 2019-04-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EtherSplitApp', '0003_auto_20190408_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, default='', max_length=6)),
                ('currency', models.CharField(blank=True, choices=[('holla', 'Holla'), ('shi', 'Shi'), ('credit-stick', 'Credit Stick')], max_length=32)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('target', models.CharField(blank=True, choices=[('self', 'Self'), ('target', 'Target')], max_length=32)),
                ('damage', models.CharField(blank=True, default='', max_length=4)),
                ('aoe_radius', models.CharField(blank=True, default='', max_length=4)),
                ('mana_cost', models.CharField(blank=True, default='', max_length=4)),
                ('duration', models.CharField(blank=True, default='', help_text='Number of turns the ability lasts.', max_length=4)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='aoe_distance',
            new_name='aoe_radius',
        ),
        migrations.RenameField(
            model_name='ability',
            old_name='turns',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='aoe_distance',
            new_name='aoe_radius',
        ),
        migrations.AddField(
            model_name='character',
            name='lucky_number',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
