# Generated by Django 2.1.5 on 2019-04-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0004_auto_20190409_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default='temp', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
