# Generated by Django 2.1.5 on 2019-04-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0006_auto_20190410_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character'),
        ),
    ]
