# Generated by Django 2.1.5 on 2019-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0011_auto_20190410_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
        migrations.AlterField(
            model_name='ability',
            name='duration',
            field=models.CharField(blank=True, choices=[('instant', 'Instant'), ('1turn', '1 Turn'), ('2turn', '2 Turn'), ('3turn', '3 Turn'), ('4turn', '4 Turn'), ('5turn', '5 Turn')], default='', help_text='Number of turns the ability lasts.', max_length=8),
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
    ]
