# Generated by Django 2.1.5 on 2019-04-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0012_auto_20190410_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='duration',
            field=models.CharField(blank=True, choices=[('instant', 'Instant'), ('1turn', '1 Turn'), ('2turn', '2 Turns'), ('3turn', '3 Turns'), ('4turn', '4 Turns'), ('5turn', '5 Turns')], default='', help_text='Number of turns the ability lasts.', max_length=8),
        ),
    ]
