# Generated by Django 2.0.6 on 2019-04-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0014_rule_for_gm_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str', models.CharField(blank=True, default='', help_text='Strength', max_length=4)),
                ('end', models.CharField(blank=True, default='', help_text='Endurance', max_length=4)),
                ('agi', models.CharField(blank=True, default='', help_text='Agility', max_length=4)),
                ('spd', models.CharField(blank=True, default='', help_text='Speed', max_length=4)),
                ('cog', models.CharField(blank=True, default='', help_text='Cognition', max_length=4)),
                ('wis', models.CharField(blank=True, default='', help_text='Wisdom', max_length=4)),
                ('mag', models.CharField(blank=True, default='', help_text='Magnetism', max_length=4)),
                ('flo', models.CharField(blank=True, default='', help_text='Flow', max_length=4)),
                ('luk', models.CharField(blank=True, default='', help_text='Luck', max_length=4)),
                ('wil', models.CharField(blank=True, default='', help_text='Will', max_length=4)),
                ('chi', models.CharField(blank=True, default='', help_text='Chi', max_length=4)),
                ('syn', models.CharField(blank=True, default='', help_text='Syncro', max_length=4)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EtherSplitApp.Character')),
            ],
            options={
                'verbose_name_plural': 'Character Stats',
            },
        ),
        migrations.AddField(
            model_name='gear',
            name='body_part',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('chest', 'Chest'), ('left_arm', 'Left Arm'), ('right_arm', 'Right Arm'), ('arms', 'Arms'), ('waist', 'Waist'), ('left_leg', 'Left Leg'), ('right_leg', 'Right Leg'), ('legs', 'legs'), ('hands', 'Hands'), ('feet', 'Feet')], default='', max_length=12),
        ),
    ]
