# Generated by Django 2.1.5 on 2019-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0015_auto_20190413_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
