# Generated by Django 2.1.5 on 2019-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0016_auto_20190416_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
    ]
