# Generated by Django 2.1.5 on 2019-04-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0017_ability_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('instant', 'Instant'), ('1turn', '1 Turn'), ('2turn', '2 Turns'), ('3turn', '3 Turns'), ('4turn', '4 Turns'), ('5turn', '5 Turns')], default='', max_length=8),
        ),
    ]
