# Generated by Django 2.1.5 on 2019-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0018_auto_20190416_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, choices=[('0', 'Instant'), ('1', '1 Turn'), ('2', '2 Turns'), ('3', '3 Turns'), ('4', '4 Turns'), ('5', '5 Turns')], default='', max_length=8),
        ),
    ]
