# Generated by Django 2.1.5 on 2019-04-18 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0019_auto_20190416_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='hit_points',
            new_name='health_points',
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='hit_points',
            new_name='health_points',
        ),
    ]
