# Generated by Django 2.1.5 on 2019-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0020_auto_20190418_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='aoe_radius',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='ability',
            name='charges',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='ability',
            name='damage',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='character',
            name='health_points',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='gear',
            name='armor',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='gear',
            name='health_points',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='aoe_radius',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='charges',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='money',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='spell',
            name='aoe_radius',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='spell',
            name='damage',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='spell',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='Number of turns the ability lasts.', max_length=8),
        ),
        migrations.AlterField(
            model_name='spell',
            name='mana_cost',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammo',
            field=models.CharField(blank=True, default='', help_text="Put 'melee' if melee weapon.", max_length=8),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
