# Generated by Django 2.0.6 on 2019-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0021_auto_20190418_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='body_part',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('neck', 'Neck'), ('chest', 'Chest'), ('left_arm', 'Left Arm'), ('right_arm', 'Right Arm'), ('arms', 'Arms'), ('waist', 'Waist'), ('left_leg', 'Left Leg'), ('right_leg', 'Right Leg'), ('legs', 'legs'), ('hands', 'Hands'), ('feet', 'Feet')], default='', max_length=12),
        ),
    ]
