# Generated by Django 2.1.5 on 2019-05-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0023_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EtherSplitApp.Character'),
        ),
    ]
