# Generated by Django 2.0.6 on 2019-05-10 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EtherSplitApp', '0024_auto_20190510_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companion',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='EtherSplitApp.Character'),
        ),
    ]
